name = "DecayAngles"
uuid = "b554e927-dfdc-487d-b897-432a0f9e843f"
authors = ["Mikhail Mikhasenko <mikhail.mikhasenko@cern.ch>"]
version = "0.2.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
FourVectors = "b122eb78-8380-428a-b8c8-584a022ae8b6"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"

[compat]
AbstractTrees = "0.4.5"
FourVectors = "0.3.0"
Parameters = "0.12.3"
Setfield = "1.1.1"
